dateModified: 1738659450
email:
  fromEmail: support@craftcms.com
  fromName: 'Craft test site'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0ec9b1fd-034b-4a84-99af-1758de94e5da: 'Magic login testing' # Magic login testing
    2eb44645-1260-46fe-9ca5-5f80e350f1b7: 'Magic login testing' # Magic login testing
plugins:
  magic-login:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
system:
  edition: pro
  live: true
  name: 'Magic login testing'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
